// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/trip.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6081960130526898337),
    name: 'Trip',
    lastPropertyId: const obx_int.IdUid(19, 806433669376805625),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3271823968218708102),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 833008033422000966),
        name: 'trainNo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9167964571566880170),
        name: 'boardStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1995894907278946645),
        name: 'alightStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1870405879240513879),
        name: 'originStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4203458901813979873),
        name: 'destStation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3450126195387970900),
        name: 'departureTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4492059836529176936),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2987167184175118123),
        name: 'trainCategoryKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1446348425299778026),
        name: 'trainPlatformKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3510166469952034715),
        name: 'trainSeriesKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8298691315894226537),
        name: 'trainVariant',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2494311643034467425),
        name: 'bureauKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 289532781612152040),
        name: 'sectionName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7257946501693887664),
        name: 'seatCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1391274159911297497),
        name: 'seatType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 808421478790260987),
        name: 'trainType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6426177717519949256),
        name: 'remarks',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 806433669376805625),
        name: 'arrivalTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6081960130526898337),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Trip: obx_int.EntityDefinition<Trip>(
      model: _entities[0],
      toOneRelations: (Trip object) => [],
      toManyRelations: (Trip object) => {},
      getId: (Trip object) => object.id,
      setId: (Trip object, int id) {
        object.id = id;
      },
      objectToFB: (Trip object, fb.Builder fbb) {
        final trainNoOffset = fbb.writeString(object.trainNo);
        final boardStationOffset = fbb.writeString(object.boardStation);
        final alightStationOffset = fbb.writeString(object.alightStation);
        final originStationOffset = fbb.writeString(object.originStation);
        final destStationOffset = fbb.writeString(object.destStation);
        final trainCategoryKeyOffset = fbb.writeString(object.trainCategoryKey);
        final trainPlatformKeyOffset = object.trainPlatformKey == null
            ? null
            : fbb.writeString(object.trainPlatformKey!);
        final trainSeriesKeyOffset = object.trainSeriesKey == null
            ? null
            : fbb.writeString(object.trainSeriesKey!);
        final trainVariantOffset = object.trainVariant == null
            ? null
            : fbb.writeString(object.trainVariant!);
        final bureauKeyOffset = object.bureauKey == null
            ? null
            : fbb.writeString(object.bureauKey!);
        final sectionNameOffset = object.sectionName == null
            ? null
            : fbb.writeString(object.sectionName!);
        final seatCategoryOffset = fbb.writeString(object.seatCategory);
        final seatTypeOffset = fbb.writeString(object.seatType);
        final trainTypeOffset = fbb.writeString(object.trainType);
        final remarksOffset = fbb.writeString(object.remarks);
        fbb.startTable(20);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, trainNoOffset);
        fbb.addOffset(2, boardStationOffset);
        fbb.addOffset(3, alightStationOffset);
        fbb.addOffset(4, originStationOffset);
        fbb.addOffset(5, destStationOffset);
        fbb.addInt64(6, object.departureTime.millisecondsSinceEpoch);
        fbb.addFloat64(7, object.price);
        fbb.addOffset(8, trainCategoryKeyOffset);
        fbb.addOffset(9, trainPlatformKeyOffset);
        fbb.addOffset(10, trainSeriesKeyOffset);
        fbb.addOffset(11, trainVariantOffset);
        fbb.addOffset(12, bureauKeyOffset);
        fbb.addOffset(13, sectionNameOffset);
        fbb.addOffset(14, seatCategoryOffset);
        fbb.addOffset(15, seatTypeOffset);
        fbb.addOffset(16, trainTypeOffset);
        fbb.addOffset(17, remarksOffset);
        fbb.addInt64(18, object.arrivalTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final arrivalTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          40,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final trainNoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final boardStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final alightStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final originStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final destStationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final departureTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final arrivalTimeParam = arrivalTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(arrivalTimeValue);
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final trainCategoryKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final trainPlatformKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final trainSeriesKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final trainVariantParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final bureauKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final sectionNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final seatCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final seatTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final trainTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final remarksParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final object = Trip(
          id: idParam,
          trainNo: trainNoParam,
          boardStation: boardStationParam,
          alightStation: alightStationParam,
          originStation: originStationParam,
          destStation: destStationParam,
          departureTime: departureTimeParam,
          arrivalTime: arrivalTimeParam,
          price: priceParam,
          trainCategoryKey: trainCategoryKeyParam,
          trainPlatformKey: trainPlatformKeyParam,
          trainSeriesKey: trainSeriesKeyParam,
          trainVariant: trainVariantParam,
          bureauKey: bureauKeyParam,
          sectionName: sectionNameParam,
          seatCategory: seatCategoryParam,
          seatType: seatTypeParam,
          trainType: trainTypeParam,
          remarks: remarksParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Trip] entity fields to define ObjectBox queries.
class Trip_ {
  /// See [Trip.id].
  static final id = obx.QueryIntegerProperty<Trip>(_entities[0].properties[0]);

  /// See [Trip.trainNo].
  static final trainNo = obx.QueryStringProperty<Trip>(
    _entities[0].properties[1],
  );

  /// See [Trip.boardStation].
  static final boardStation = obx.QueryStringProperty<Trip>(
    _entities[0].properties[2],
  );

  /// See [Trip.alightStation].
  static final alightStation = obx.QueryStringProperty<Trip>(
    _entities[0].properties[3],
  );

  /// See [Trip.originStation].
  static final originStation = obx.QueryStringProperty<Trip>(
    _entities[0].properties[4],
  );

  /// See [Trip.destStation].
  static final destStation = obx.QueryStringProperty<Trip>(
    _entities[0].properties[5],
  );

  /// See [Trip.departureTime].
  static final departureTime = obx.QueryDateProperty<Trip>(
    _entities[0].properties[6],
  );

  /// See [Trip.price].
  static final price = obx.QueryDoubleProperty<Trip>(
    _entities[0].properties[7],
  );

  /// See [Trip.trainCategoryKey].
  static final trainCategoryKey = obx.QueryStringProperty<Trip>(
    _entities[0].properties[8],
  );

  /// See [Trip.trainPlatformKey].
  static final trainPlatformKey = obx.QueryStringProperty<Trip>(
    _entities[0].properties[9],
  );

  /// See [Trip.trainSeriesKey].
  static final trainSeriesKey = obx.QueryStringProperty<Trip>(
    _entities[0].properties[10],
  );

  /// See [Trip.trainVariant].
  static final trainVariant = obx.QueryStringProperty<Trip>(
    _entities[0].properties[11],
  );

  /// See [Trip.bureauKey].
  static final bureauKey = obx.QueryStringProperty<Trip>(
    _entities[0].properties[12],
  );

  /// See [Trip.sectionName].
  static final sectionName = obx.QueryStringProperty<Trip>(
    _entities[0].properties[13],
  );

  /// See [Trip.seatCategory].
  static final seatCategory = obx.QueryStringProperty<Trip>(
    _entities[0].properties[14],
  );

  /// See [Trip.seatType].
  static final seatType = obx.QueryStringProperty<Trip>(
    _entities[0].properties[15],
  );

  /// See [Trip.trainType].
  static final trainType = obx.QueryStringProperty<Trip>(
    _entities[0].properties[16],
  );

  /// See [Trip.remarks].
  static final remarks = obx.QueryStringProperty<Trip>(
    _entities[0].properties[17],
  );

  /// See [Trip.arrivalTime].
  static final arrivalTime = obx.QueryDateProperty<Trip>(
    _entities[0].properties[18],
  );
}
